
name: Export Godot Project

on:
  push:
    branches:
      - main

jobs:
  export-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Export Godot project
        uses: firebelley/godot-export@v5
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.5/Godot_v4.5-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.5/Godot_v4.5-stable_export_templates.tpz
          create_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
